before_all do
  ensure_git_branch(branch: 'test/fastlane')
  ensure_git_status_clean
  git_pull
end

platform :ios do
  private_lane :staging_build do
    increment_build_number_in_plist(xcodeproj: './ios/fastlane.xcodeproj', target: 'fastlane')
    configuration = 'Debug'
    xcodebuild(scheme: 'fastlane',
               workspace: './ios/fastlane.xcworkspace',
               xcargs: "-configuration #{configuration} -sdk 'iphonesimulator15.0' -destination 'platform=iOS Simulator, name=iPhone 12 Pro Max, OS=15.0'"
           )
  end

  lane :beta do
    staging_build
  end
end